version: 2.1
orbs:
  #  node: circleci/node@4.1.0
  gcp-gke: circleci/gcp-gke@1.1.0
  gcr: circleci/gcp-gcr@0.9.0
jobs:
  build:
    #    working_directory: ~/test-project
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-npm
          command: pwd && npm install
  #  build:
  #    description: Install npm
  #    # machine option runs your jobs in a dedicated, ephemeral VM that has the following specifications:
  #    machine: true
  #    steps:
  #      - checkout
  #      # Install node
  #      - node/install
  #      # Download and cache dependencies
  #      - node/install-packages
  Build-Push-Image-Docker:
    description: Build and push image to Google Container Registry
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          image: app
          tag: "v3" #Change version number e.g to 'v3' when updating application
      - gcr/push-image:
          image: app
          tag: "v3" #Change version number e.g to 'v3' when updating application

  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      # Install `gcloud` and `kubectl` if not already installed.
      - gcp-gke/install
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: labourify-cluster
          perform-login: true
      # Initialize the `gcloud` CLI.
      #      - gcp-gke/init
      # Update a deployment Docker image.
      - gcp-gke/rollout-image:
          cluster: labourify-cluster
          container: labourify-backend
          deployment: labourify-backend
          image: gcr.io/labourify/app # change version when updating
          tag: "v3"
workflows:
  build_update_deploy:
    jobs:
      - build
      - Build-Push-Image-Docker:
          requires:
            - build
      - deploy:
          requires:
            - Build-Push-Image-Docker
